name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Ruby Tests
    runs-on: ubuntu-latest

    env:
      PG_DATABASE: diydex_test
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      RAILS_ENV: test

    services:
      postgres:
        env:
          POSTGRES_DB: diydex_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install Dependencies
        run: bundle install
      - name: Prepare Database
        run: bin/rails test:prepare
      - name: Run Tests
        run: bundle exec rake test


  deploy:
    needs: test
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
